services:
  ctfd:
    image: ctfd/ctfd
    user: root # TODO: fix permission issues
    restart: unless-stopped
    init: true
    entrypoint: /entry.sh
    environment:
      DISCORD_WEBHOOK_URL: "" # TODO: replace with your webhook URL
      DISCORD_WEBHOOK_LIMIT: "50" # announce first N solves
      DISCORD_WEBHOOK_MESSAGE: "{user} solved {challenge}! ({solves} solves total)"
    volumes:
      - ./ctfd/entry.sh:/entry.sh
      - mcc-ctfd:/opt/storage
      - ./ctfd/plugins/ctfd-discord-webhook-plugin:/opt/CTFd/CTFd/plugins/ctfd-discord-webhook-plugin:ro

  backend:
    build: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # CTF problem ports
      - "9500:9500" # syoch.vulnerable_rsa3
      - "9501:9501" # syoch.vulnerable_rsa2
      - "9502:9502" # syoch.vulnerable_rsa1
      - "9503:9503" # syoch.termination
      - "9504:9504" # syoch.hello_ctf
      - "9505:9505" # syoch.c0rrupt_stack
      - "9506:9506" # syoch.basic_exploitation
    init: true
    command: /app/run_server.sh
    restart: unless-stopped

  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-www:/var/www/certbot
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - ctfd
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-www:/var/www/certbot

volumes:
  mcc-ctfd:
