version: '3.8'

services:
  ctfd:
    image: ctfd/ctfd
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - ctf-network

  backend:
    build:
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    init: true
    command: /app/run_server.sh
    entrypoint: ["/bin/bash"]
    restart: unless-stopped
    networks:
      - ctf-network

  work:
    build:
      context: work
      dockerfile: Dockerfile
    ports:
      - "38192:22"
    init: true
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge