services:
  ctfd:
    image: ctfd/ctfd
    user: root # TODO: fix permission issues
    ports:
      - 8000:8000
    restart: unless-stopped
    init: true
    entrypoint: /entry.sh
    volumes:
      - ./ctfd/entry.sh:/entry.sh
      - mcc-ctfd:/opt/storage

  backend:
    build: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3030:3000
    init: true
    command: /app/run_server.sh
    restart: unless-stopped

volumes:
  mcc-ctfd:
